### ISSUE TITLE
04 - blackjack - week 1 project

### ISSUE THREAD

**Issue by KamariRoss** [KamariRoss/assignments#5]
# Blackjack

In this project, you are creating a playable game of [Blackjack](https://en.wikipedia.org/wiki/Blackjack).

## Objectives

- Practice the skills and ideas you have learned so far
- Effectively use loops, conditionals, and other control structures to implement [control flows](https://en.wikipedia.org/wiki/Control_flow)
- Demonstrate usage of data structures to model resources

## Requirements

Create a single-player blackjack game that plays against the house, i.e., a human player and computer dealer. You are free to create the user interface however you want, **but keep it simple for Explorer Mode**.

### Explorer Mode

General Rules:

- [x] The game should be played with a standard deck of playing cards (52).
- [x] The house should be dealt with two cards, hidden from the player until the house reveals its hand.
- [x] The player should be dealt with two cards, visible to the player.
- [x] The player should have a chance to hit (i.e., be dealt another card) until they decide to stop or they _bust_ (i.e., their total is over 21 ).
- [x] When the player stands, the house reveals its hand and hit (i.e., draw cards) until they have 17 or more.
- [x] If either the house or the player bust, they lose.

- [x] The player should have two choices: "Hit" and "Stand."
- [x] Consider Aces to be worth 11, never 1.
- [x] The app should display the winner. For this mode, the winner is who is closer to a blackjack (21) without going over.
- [x] There should be an option to play again; this should reset the hands and reshuffle the deck.

### Adventure Mode

- [x] Reveal one of the house's cards to the player when cards dealt.
- [x] Consider aces be worth one _or_ eleven.
- [ ] Allow the player to ["Split"](https://blog.betway.com/casino/blackjack-strategy-101-how-do-you-split-in-blackjack/).
- [x] Improve the win requirements. From Wikipedia:
  > Players win by not busting and having a total higher than the dealer, or not busting and having the dealer bust, or getting a blackjack without the dealer getting a blackjack. If the player and dealer have the same total (not counting blackjacks), this is called a "push," and the player typically does not win or lose money on that hand. Otherwise, the dealer wins.

### Epic Mode

- [ ] Add a betting system that carries between rounds
- [ ] Allow the player to "Double down" or "Surrender."
- [ ] Add more Players

**Comment by KamariRoss** [comment]
https://github.com/KamariRoss/BlackJack

**Comment by mdewey** [comment]
Everything above [line 92](https://github.com/KamariRoss/BlackJack/blob/master/Program.cs#L92) looks pretty good. 

Past that line, there are correct ideas, but in the wrong order. Before we check the endgame conditions,  we need to have a game. I recommend removing the giant if statements and just start with something really simple. Start dealing cards to a user until they say "stay". Once that works then add the limit for up to 21. 

After the player logic is sound, then we want to add the dealer logic. This will after the player logic.


These are your two next big steps.

**Comment by mdewey** [comment]
A good guideline is that once your if statements start to get huge, you should look to refactor the logic.  for example, take a look at these two rock, paper, scissor logic 

Example a: 
```
        if (choice == "rock")
        {
          if (playerChoice == "paper")
          {
            Console.WriteLine($"Player wins!, {playerChoice} beats {choice}");
          }
          else if (playerChoice == "rock")
          {
            Console.WriteLine($"Tie!, {choice} ties {playerChoice}");
          }
          else if (playerChoice == "scissors")
          {
            Console.WriteLine($"Computer wins!, {choice} beats {playerChoice}");
          }
        }
        else if (choice == "paper")
        {
          if (playerChoice == "scissors")
          {
            Console.WriteLine($"Player wins!, {playerChoice} beats {choice}");
          }
          else if (playerChoice == "paper")
          {
            Console.WriteLine($"Tie!, {choice} ties {playerChoice}");
          }
          else if (playerChoice == "rock")
          {
            Console.WriteLine($"Computer wins!, {choice} beats {playerChoice}");
          }
        }
        else if (choice == "scissors")
        {
          if (playerChoice == "rock")
          {
            Console.WriteLine($"Player wins!, {playerChoice} beats {choice}");
          }
          else if (playerChoice == "scissors")
          {
            Console.WriteLine($"Tie!, {choice} ties {playerChoice}");
          }
          else if (playerChoice == "paper")
          {
            Console.WriteLine($"Computer wins!, {choice} beats {playerChoice}");
          }
        }
      
```

Example B 
```
if (choice == "rock" && playerChoice == "paper") {
  Console.WriteLine($"Player wins!, {playerChoice} beats {choice}");
}
else if (choice == "rock" && playerChoice == "rock") {
  Console.WriteLine($"Tie!, {choice} ties {playerChoice}");
}
else if (choice == "rock" && playerChoice == "scissors")
{
  Console.WriteLine($"Computer wins!, {choice} beats {playerChoice}");
}
else if (choice == "paper" && playerChoice == "scissors")
{
  Console.WriteLine($"Player wins!, {playerChoice} beats {choice}");
}
else if (choice == "paper" && playerChoice == "paper")
{
  Console.WriteLine($"Tie!, {choice} ties {playerChoice}");
}
else if (choice == "paper" && playerChoice == "rock")
{
  Console.WriteLine($"Computer wins!, {choice} beats {playerChoice}");
}
else if (choice == "scissors" &&  playerChoice == "rock")
{
  Console.WriteLine($"Player wins!, {playerChoice} beats {choice}");
}
else if (choice == "scissors" && playerChoice == "scissors")
{
  Console.WriteLine($"Tie!, {choice} ties {playerChoice}");
}
else if (choice == "scissors" && playerChoice == "paper")
{
  Console.WriteLine($"Computer wins!, {choice} beats {playerChoice}");
}
``` 

Both do the same thing, but in Example A, we are reducing the noise of duplicate logic by nesting our if statements.
